CI(deps): Update dependency pylint to v3 (#3820)
* Format pyproject.toml

* Checks: Add note on MIN_PYTHON_VERSION

* Configure Pyright type checker

* CQ: Create default pylint config in pyproject.toml

* CQ: Port root pylint config to pyproject.toml

* CI(pylint): Update versions in workflow

* CI: Run Pylint on all project with source-roots configuration and ignore-paths

* CI(pylint): Do not use star glob for wxGUI pylint call

* Clear pylint config and reset to defaults

Set GRASS-specific overrides and comment out defaults

* CQ: Enable pylint plugins

* Set pylint's output-format to colorized

* CQ: Set pylint source-roots and ignore-paths

CQ: Set pylint ignore-paths to ignore libgrass_interface_generator and OBJ.* folders, and ignore Makefiles

* Checks: Rename pylint rules that were renamed

* Checks: Adjust outdated inline pylint exclusions

* Checks: Change pylint folder ignores

Checks: Also ignore .pytest_cache folder for pylint

* Checks: Disable all failing pylint rules

* CI(pylint): Remove rcfile argument from pytest pylint call

CI(pylint): Comment out pylint ignore arguments from pytest pylint call

* CI(pylint): Do not change into subdirectory for grass and gui

* CI(pylint): Run pylint on other files before slower wxGUI

* CI(pylint): Only run pylint once for all code

* checks: Remove non-modified pylint config

* style: Change misplaced docstring to comment in pygrass/rpc/__init__.py

* grass.script: Ignore signature-differs pylint warning in array.py

* grass.imaging.images2gif: Fix Pylint using-constant-test

* grass.jupyter.utils: Fix pylint redefined-variable-type (R0204) of output variable

Pylint 3.2.6 error: R0204: Redefinition of output type from bytes to grass.script.utils.KeyValue (redefined-variable-type)

Adds typing to the function analyzed, and also to the return type of the gs.parse_key_val() used.

* grass.script.db: Close opened file in db_connection

* t.unregister: Open file with context handler (SIM115)

* Typing improvement

* Fix typo of BufferedMapWindow in gui/wxpython/mapdisp/test_mapdisp.py

* pylint: Add pylint skip-file directive in generated file wxpython/menustrings.py
pylint: Ignore generated file wxpython/menustrings.py

* utils: Add timeout to requests.get

* grass.script.core: Fix E0606: Possibly using variable 'ps' before assignment (possibly-used-before-assignment)

Co-authored-by: Edouard Choinière <27212526+echoix@users.noreply.github.com>